pool: 
   vmImage: windows-latest

variables:
 - name: spnName
   value: 'pipelines-runner'
 - name: blueprintsPath
   value: '.\samples\'
 - name: blueprintName
   value: '101-boilerplate'
 - name: subscriptionId
   value: '54ff4cf6-32b8-4112-ac42-05a514813214' # / Contoso IT - SH360 - Prod

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    exclude:
    - README.md
    - LICENSE
    - .gitignore
    - .github/*

steps:

- task: CreateBlueprint@1
  inputs:
    azureSubscription: 'Govardhan – MPN (54ff4cf6-32b8-4112-ac42-05a514813214)'
    BlueprintName: '$(blueprintName)'
    BlueprintPath: '$(blueprintsPath)$(blueprintName)'
    AlternateLocation: false
    PublishBlueprint: true

- task: AssignBlueprint@1
  inputs:
    azureSubscription: 'Govardhan – MPN (54ff4cf6-32b8-4112-ac42-05a514813214)'
    AssignmentName: 'pla-$(blueprintName)'
    BlueprintName: '$(blueprintName)'
    ParametersFile: '$(blueprintsPath)$(blueprintName)\assign.json'
    AlternateSubscription: true
    SubscriptionID: '$(subscriptionId)'